# Generated by Django 6.0.5 on 2026-05-11 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_created_at_server_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='started_at_utc',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='time_class',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='time_control_base_s',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='time_control_increment_s',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GameMoveTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ply', models.IntegerField()),
                ('time_spent_ms', models.IntegerField()),
                ('clock_after_ms', models.IntegerField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='move_times', to='games.game')),
            ],
            options={
                'verbose_name': 'Game Move Time',
                'verbose_name_plural': 'Game Move Times',
                'db_table': 'game_move_times',
                'unique_together': {('game', 'ply')},
            },
        ),
    ]
