# Generated by Django 6.0.5 on 2026-05-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_time_fields_and_move_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemovetime',
            name='clock_after_ms',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamemovetime',
            name='time_spent_ms',
            field=models.BigIntegerField(),
        ),
    ]
