# Generated by Django 6.0.5 on 2026-05-20 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_widen_move_time_to_bigint'),
        ('openings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='opening',
            field=models.ForeignKey(blank=True, help_text='Resolved OpeningBook entry — denormalised at ingest by games.opening_resolver.resolve_opening_id.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='openings.openingbook'),
        ),
    ]
