# Generated by Django 6.0.3 on 2026-05-02 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eco', models.CharField(db_index=True, max_length=8)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('pgn', models.TextField()),
                ('epd', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Opening',
                'verbose_name_plural': 'Openings',
                'db_table': 'opening_book',
                'ordering': ['eco', 'name'],
            },
        ),
    ]
