# Generated by Django 6.0.5 on 2026-05-21 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerAPIKey',
            fields=[
                ('id', models.CharField(editable=False, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('prefix', models.CharField(editable=False, max_length=8, unique=True)),
                ('hashed_key', models.CharField(editable=False, max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('name', models.CharField(default=None, help_text='A free-form name for the API key. Need not be unique. 50 characters max.', max_length=50)),
                ('revoked', models.BooleanField(blank=True, default=False, help_text='If the API key is revoked, clients cannot use it anymore. (This cannot be undone.)')),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Once API key expires, clients cannot use it anymore.', null=True, verbose_name='Expires')),
                ('worker_name', models.CharField(max_length=128)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Worker API Key',
                'verbose_name_plural': 'Worker API Keys',
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkerLogUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('bucket_key', models.CharField(max_length=512)),
                ('size_bytes', models.PositiveIntegerField()),
                ('note', models.TextField(blank=True)),
                ('reason', models.CharField(choices=[('crash', 'crash'), ('manual', 'manual')], max_length=16)),
                ('worker_version', models.CharField(blank=True, max_length=32)),
                ('host_summary', models.JSONField(default=dict)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_uploads', to='api.workerapikey')),
            ],
            options={
                'verbose_name': 'Worker Log Upload',
                'verbose_name_plural': 'Worker Log Uploads',
                'ordering': ('-uploaded_at',),
            },
        ),
    ]
