# Generated by Django 6.0.5 on 2026-05-13 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerLogUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('bucket_key', models.CharField(max_length=512)),
                ('size_bytes', models.PositiveIntegerField()),
                ('note', models.TextField(blank=True)),
                ('reason', models.CharField(choices=[('crash', 'crash'), ('manual', 'manual')], max_length=16)),
                ('worker_version', models.CharField(blank=True, max_length=32)),
                ('host_summary', models.JSONField(default=dict)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_uploads', to='api.workerapikey')),
            ],
            options={
                'verbose_name': 'Worker Log Upload',
                'verbose_name_plural': 'Worker Log Uploads',
                'ordering': ('-uploaded_at',),
            },
        ),
    ]
