# Generated by Django 6.0.5 on 2026-05-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_enqueue_stockfish', models.BooleanField(default=True, help_text='Auto-enqueue Stockfish AnalysisJob for newly ingested games.')),
                ('auto_enqueue_lc0', models.BooleanField(default=False, help_text='Auto-enqueue Lc0 AnalysisJob for newly ingested games.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
                'db_table': 'site_settings',
            },
        ),
    ]
