# Generated by Django 6.0.5 on 2026-05-22 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='auto_enqueue_lc0',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='auto_enqueue_stockfish',
        ),
    ]
