# Generated by Django 6.0.5 on 2026-05-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moveanalysis',
            name='arrow_cp_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moveanalysis',
            name='arrow_cp_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moveanalysis',
            name='arrow_cp_3',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
