# Generated by Django 6.0.5 on 2026-05-09 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_analysisjob_claimed_at_and_more'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='analysisjob',
            name='analysis_jo_status_e13d4b_idx',
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='dispatch_mode',
            field=models.CharField(choices=[('pull', 'Pull'), ('runpod', 'RunPod')], db_index=True, default='pull', help_text='pull = claimed via API by local workers; runpod = submitted by dispatcher', max_length=16),
        ),
        migrations.AddIndex(
            model_name='analysisjob',
            index=models.Index(fields=['status', 'engine', 'dispatch_mode'], name='analysis_jo_status_0bfd78_idx'),
        ),
    ]
