# Generated by Django 6.0.5 on 2026-05-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_add_dispatch_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='last_error',
            field=models.TextField(blank=True, help_text='Most recent RunPod submission error, if any. Job stays pending for retry.', null=True),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='last_error_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
