# Generated by Django 6.0.5 on 2026-05-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_analysisjob_last_error_analysisjob_last_error_at'),
        ('games', '0002_add_game_created_at'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='analysisjob',
            name='analysis_jo_status_0bfd78_idx',
        ),
        migrations.AddIndex(
            model_name='analysisjob',
            index=models.Index(fields=['status', 'engine'], name='analysis_jo_status_e13d4b_idx'),
        ),
        migrations.RemoveField(
            model_name='analysisjob',
            name='dispatch_mode',
        ),
    ]
