# Generated by Django 6.0.5 on 2026-05-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_remove_analysisjob_analysis_jo_status_0bfd78_idx_and_more'),
        ('games', '0005_widen_move_time_to_bigint'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='analysisjob',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'running', 'submitted'])), fields=('game', 'engine'), name='analysis_jobs_active_engine_unique'),
        ),
    ]
