# Generated by Django 6.0.5 on 2026-05-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_analysisjob_analysis_jobs_active_engine_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerheartbeat',
            name='batch_processed',
            field=models.IntegerField(default=0, help_text='Jobs completed so far this worker session (N in N/M).'),
        ),
        migrations.AddField(
            model_name='workerheartbeat',
            name='batch_total',
            field=models.IntegerField(blank=True, help_text='Worker max_jobs run cap (M in N/M). Null = unlimited.', null=True),
        ),
        migrations.AddField(
            model_name='workerheartbeat',
            name='session_started_at',
            field=models.DateTimeField(blank=True, help_text='Wall-clock start of the current worker run/session.', null=True),
        ),
    ]
