# Generated by Django 6.0.5 on 2026-05-18 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_workerheartbeat_batch_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('max_jobs', models.IntegerField(blank=True, help_text='Per-run job cap; null → settings.VAST_MAX_JOBS.', null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Analysis Schedule',
                'verbose_name_plural': 'Analysis Schedules',
                'db_table': 'analysis_schedules',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('launching', 'Launching'), ('running', 'Running'), ('destroyed', 'Destroyed'), ('failed', 'Failed')], db_index=True, default='launching', max_length=16)),
                ('vast_instance_id', models.CharField(blank=True, help_text="vast 'new_contract' id; null until create succeeds.", max_length=32, null=True)),
                ('launched_at', models.DateTimeField(blank=True, null=True)),
                ('hard_deadline', models.DateTimeField(blank=True, null=True)),
                ('destroyed_at', models.DateTimeField(blank=True, null=True)),
                ('offer_dph', models.FloatField(blank=True, help_text='$/hr actually accepted, for cost visibility.', null=True)),
                ('launch_worker_ids', models.JSONField(blank=True, default=list, help_text='WorkerHeartbeat.worker_id set known at launch (for drained-by-stale-heartbeat correlation).')),
                ('worker_id', models.CharField(blank=True, help_text='The WorkerHeartbeat bound to this instance once a post-launch worker appears; null until correlated.', max_length=64, null=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='analysis.analysisschedule')),
            ],
            options={
                'verbose_name': 'Analysis Instance',
                'verbose_name_plural': 'Analysis Instances',
                'db_table': 'analysis_instances',
                'ordering': ['-created_at'],
            },
        ),
    ]
