# Generated by Django 6.0.5 on 2026-05-18 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0009_analysisschedule_analysisinstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringAnalysisSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('crontab', models.CharField(help_text="5-field cron expression, e.g. '0 2 * * 1' (Mon 02:00).", max_length=128)),
                ('timezone', models.CharField(default='UTC', help_text='IANA tz name the crontab is evaluated in.', max_length=64)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('max_jobs', models.IntegerField(blank=True, help_text='Per-run job cap; null → settings.VAST_MAX_JOBS.', null=True)),
                ('last_materialized_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Recurring Analysis Schedule',
                'verbose_name_plural': 'Recurring Analysis Schedules',
                'db_table': 'recurring_analysis_schedules',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='analysisschedule',
            name='recurring_rule',
            field=models.ForeignKey(blank=True, help_text='Set when this row was materialized from a recurring rule; null for one-offs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materialized_schedules', to='analysis.recurringanalysisschedule'),
        ),
    ]
