# Generated by Django 6.0.5 on 2026-05-20 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0011_lc0_wdl_calibration'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_name', models.CharField(max_length=64)),
                ('settings_hash', models.CharField(max_length=64)),
                ('draw_rate_reference', models.FloatField(help_text='Population draw rate measured by the sampler; in (0.001, 0.999).')),
                ('sample_size', models.IntegerField(help_text='Positions sampled before convergence or max_positions cap.')),
                ('sem', models.FloatField(help_text='Standard error of the mean achieved by the sampler.')),
                ('sampler_version', models.CharField(help_text='Echoes settings.WL_LC0_DRAW_RATE_SAMPLER_VERSION at measure time.', max_length=32)),
                ('measured_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by_worker_id', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Network Calibration',
                'verbose_name_plural': 'Network Calibrations',
                'db_table': 'network_calibration',
                'unique_together': {('network_name', 'settings_hash')},
            },
        ),
    ]
