# Generated by Django 6.0.5 on 2026-05-20 02:17
#
# Phase F of issue #161 — drop-and-rebuild migration.
#
# The first operation (RunSQL) is the policy step: per #161's "no backfill,
# no compat shim" direction, every existing row is cleared before the column
# set changes. New worker + new app deploy together as a hard cutover.
#
# CASCADE truncates the four analysis tables in one statement so the child
# tables (move_analysis, lc0_move_analysis) go with the parents
# (game_analysis, lc0_game_analysis) without ordering ceremony. Reverse_sql
# is a no-op — there is no data to put back.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0012_network_calibration'),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "TRUNCATE TABLE move_analysis, game_analysis, "
                "lc0_move_analysis, lc0_game_analysis "
                "RESTART IDENTITY CASCADE;"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RenameField(
            model_name='lc0moveanalysis',
            old_name='arrow_uci',
            new_name='arrow_uci_1',
        ),
        migrations.RenameField(
            model_name='moveanalysis',
            old_name='arrow_uci',
            new_name='arrow_uci_1',
        ),
        migrations.RemoveField(
            model_name='lc0moveanalysis',
            name='arrow_score_1',
        ),
        migrations.RemoveField(
            model_name='lc0moveanalysis',
            name='arrow_score_2',
        ),
        migrations.RemoveField(
            model_name='lc0moveanalysis',
            name='arrow_score_3',
        ),
        migrations.RemoveField(
            model_name='lc0moveanalysis',
            name='cp_equiv',
        ),
        migrations.RemoveField(
            model_name='lc0moveanalysis',
            name='move_win_delta',
        ),
        migrations.AddField(
            model_name='lc0moveanalysis',
            name='wdl_draw_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lc0moveanalysis',
            name='wdl_draw_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lc0moveanalysis',
            name='wdl_draw_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lc0moveanalysis',
            name='wdl_loss_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lc0moveanalysis',
            name='wdl_loss_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lc0moveanalysis',
            name='wdl_loss_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lc0moveanalysis',
            name='wdl_win_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lc0moveanalysis',
            name='wdl_win_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lc0moveanalysis',
            name='wdl_win_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moveanalysis',
            name='mate_in',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moveanalysis',
            name='move_win_delta',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
