# Generated by Django 6.0.3 on 2026-05-02 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=80, null=True, unique=True)),
                ('played_at', models.DateTimeField(db_index=True)),
                ('time_control', models.CharField(max_length=32)),
                ('white_username', models.CharField(blank=True, max_length=120, null=True)),
                ('black_username', models.CharField(blank=True, max_length=120, null=True)),
                ('white_rating', models.IntegerField(blank=True, null=True)),
                ('black_rating', models.IntegerField(blank=True, null=True)),
                ('result_pgn', models.CharField(blank=True, max_length=16, null=True)),
                ('winner_username', models.CharField(blank=True, max_length=120, null=True)),
                ('eco_code', models.CharField(default='', max_length=8)),
                ('opening_name', models.CharField(default='', max_length=120)),
                ('lichess_opening', models.CharField(blank=True, max_length=200, null=True)),
                ('pgn', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'db_table': 'games',
                'ordering': ['-played_at'],
            },
        ),
        migrations.CreateModel(
            name='GameParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=8)),
                ('opponent_username', models.CharField(max_length=120)),
                ('player_rating', models.IntegerField(blank=True, null=True)),
                ('opponent_rating', models.IntegerField(blank=True, null=True)),
                ('result', models.CharField(max_length=32)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('blunder_count', models.IntegerField(blank=True, null=True)),
                ('mistake_count', models.IntegerField(blank=True, null=True)),
                ('inaccuracy_count', models.IntegerField(blank=True, null=True)),
                ('acpl', models.FloatField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='games.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='players.player')),
            ],
            options={
                'verbose_name': 'Game Participant',
                'verbose_name_plural': 'Game Participants',
                'db_table': 'game_participants',
                'indexes': [models.Index(fields=['game'], name='game_partic_game_id_be88a6_idx'), models.Index(fields=['player'], name='game_partic_player__f0dc11_idx')],
                'unique_together': {('game', 'player')},
            },
        ),
    ]
